on:
  workflow_dispatch:
    inputs:
      export_environment:
        type: boolean
        description: Export the build environment as tar artifact that can be imported with Docker.
  # The GitHub application copy-pr-bot copies the source code for every pull request
  # into the repository. Approving such upstream pushes effectively marks code as trusted,
  # and is necessary to use the self-hosted NVIDIA runners.
  push:
    branches:
      - "pull-request/[0-9]+"

name: CI # do not change name without updating workflow_run triggers

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  setup:
    name: Load dependencies
    strategy:
      matrix:
        platform: [amd64, arm64]
        toolchain: [llvm, clang16, gcc12]
      fail-fast: false
    uses: ./.github/workflows/dev_environment.yml
    with:
      platforms: linux/${{ matrix.platform }}
      dockerfile: build/devdeps.Dockerfile
      toolchain: ${{ matrix.toolchain }}
      # needed only for the cloudposse GitHub action
      matrix_key: ${{ matrix.platform }}-${{ matrix.toolchain }}

  wheeldeps:
    name: Load wheel dependencies
    uses: ./.github/workflows/dev_environment.yml
    with:
      dockerfile: build/devdeps.manylinux.Dockerfile
      toolchain: x86_64
      build_args: |
        arch=x86_64
        distro=rhel8
        manylinux_image=quay.io/pypa/manylinux_2_28_x86_64:latest

  # This job is needed only when using the cloudposse GitHub action to read
  # the output of a matrix job. This is a workaround due to current GitHub
  # limitations that may not be needed if the work started here concludes:
  # https://github.com/actions/runner/pull/2477
  config:
    name: Configure build
    runs-on: ubuntu-latest
    needs: setup

    outputs:
      json: "${{ steps.read_json.outputs.result }}"

    steps:
      - uses: cloudposse/github-action-matrix-outputs-read@0.1.1
        id: read_json
        with:
          matrix-step-name: dev_environment

  build_and_test:
    name: Build and test
    needs: config
    strategy:
      matrix:
        platform: [amd64, arm64]
        toolchain: [llvm, clang16, gcc12]
      fail-fast: false
    uses: ./.github/workflows/test_in_devenv.yml
    with:
      platform: linux/${{ matrix.platform }}
      devdeps_cache: ${{ fromJson(needs.config.outputs.json).cache_key[format('{0}-{1}', matrix.platform, matrix.toolchain)] }}
      devdeps_archive: ${{ fromJson(needs.config.outputs.json).tar_archive[format('{0}-{1}', matrix.platform, matrix.toolchain)] }}
      export_environment: ${{ github.event_name == 'workflow_dispatch' && inputs.export_environment }}

  docker_image:
    name: Create Docker images
    needs: config
    strategy:
      matrix:
        platform: [amd64, arm64]
      fail-fast: false
    uses: ./.github/workflows/docker_images.yml
    with:
      platforms: linux/${{ matrix.platform }}
      devdeps_cache: ${{ fromJson(needs.config.outputs.json).cache_key[format('{0}-llvm', matrix.platform)] }}
      devdeps_archive: ${{ fromJson(needs.config.outputs.json).tar_archive[format('{0}-llvm', matrix.platform)] }}

  python_wheels:
    name: Create Python wheels
    needs: wheeldeps
    strategy:
      matrix:
        python_version: ['3.9', '3.11']
      fail-fast: false
    uses: ./.github/workflows/python_wheels.yml
    with:
      python_version: ${{ matrix.python_version }}
      devdeps_cache: ${{ needs.wheeldeps.outputs.cache_key }}
      devdeps_archive: ${{ needs.wheeldeps.outputs.tar_archive }}

  clean_up:
    name: Prepare cache clean-up
    runs-on: ubuntu-latest
    needs: [config, build_and_test, docker_image, wheeldeps, python_wheels]
    # We need to clean up even if the workflow is cancelled or fails.
    if: always()

    steps:
      - name: Save cache keys and metadata
        id: workflow_inputs
        run: |
          set -e
          key_matrix='${{ needs.config.outputs.json }}'
          keys=`echo $key_matrix | jq '.cache_key | to_entries | .[].value' --raw-output`
          keys+=" ${{ needs.wheeldeps.outputs.cache_key }}"
          echo "$keys" >> cache_keys.txt

          pr_number=pr_number=`echo ${{ github.ref_name }} | grep pull-request/ | grep -o [0-9]*`
          echo "pr-number: ${pr_number:-${{ github.event.pull_request.number }}}" >> metadata.txt

      - name: Upload cache keys
        uses: actions/upload-artifact@v3
        with:
          name: cache_keys_ci
          path: cache_keys.txt
          retention-days: 1
          if-no-files-found: error

      - name: Upload metadata
        uses: actions/upload-artifact@v3
        with:
          name: metadata_ci
          path: metadata.txt
          retention-days: 1
          if-no-files-found: error
