on:
  # We update the build caches during the pull_request_target event, 
  # and deploy the images via workflow dispatch on branches with deployment permissions.
  # A dispatch event is automatically triggered when the pull_request_target event
  # triggers the workflow.
  workflow_dispatch:
    inputs:
      update_registry_cache:
        type: boolean
        description: Create or update the build caches on the container registry.
        required: false
        default: false
      cache_base:
        required: false
        type: string
        description: 'The name of the branch to use as cache base.'
        default: main
      platforms:
        type: string
        description: The platforms to build the Docker images for.
        required: false
        default: linux/amd64
      create_release:
        type: string
        description: The version number of the release (e.g. 0.3.0). The version must not exist already.
        required: false
        default: ''
  # We need write permissions for packages to update the build caches of GHCR.
  # Make sure no external code is checked out as part of this workflow.
  # This trigger replaces the pull_request_target trigger in prepare_deployment.yml
  # so that we can use the NVIDIA runners to update the build caches.
  workflow_run:
    workflows:
      - PR merged
    types:
      - completed
  # Whenever we create a release branch, we want to populate the caches.
  # Unfortunately, it is not currently possible to filter by branch,
  # see also: https://github.com/orgs/community/discussions/26286
  push:
    branches:
      - 'releases/*'

name: Deployments # do not change name without updating workflow_run triggers

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.base.ref || github.ref_name }}
  cancel-in-progress: false

jobs:
  metadata:
    name: Prepare build
    runs-on: ubuntu-latest
    permissions:
      contents: read

    outputs:
      pull_request_number: ${{ steps.pr_info.outputs.pr_number }}
      pull_request_commit: ${{ steps.pr_info.outputs.pr_base }}
      cache_base: ${{ steps.build_info.outputs.cache_base }}
      update_cache: ${{ steps.build_info.outputs.update_cache }}
      platforms: ${{ steps.build_info.outputs.platforms }}
      requested_platforms: ${{ steps.build_info.outputs.requested_platforms }}
      environment: ${{ steps.build_info.outputs.environment }}

    steps:
      - name: Retrieve PR info
        if: github.event_name == 'workflow_run'
        id: pr_info
        run: |
          artifacts_url=${{ github.event.workflow_run.artifacts_url }}
          artifacts=$(gh api $artifacts_url -q '.artifacts[] | {name: .name, url: .archive_download_url}')

          for artifact in `echo "$artifacts"`; do
            name=`echo $artifact | jq -r '.name'`
            if [ "$name" == "metadata_pr" ]; then
              url=`echo $artifact | jq -r '.url'`
              gh api $url > metadata.zip
              unzip -d metadata metadata.zip
              for file in `find metadata/ -type f`; do
                cat "$file" >> metadata.txt
              done
              pr_number=`cat metadata.txt | grep -o 'pr-number: \S*' | cut -d ' ' -f 2`
              pr_base=`cat metadata.txt | grep -o 'pr-base: \S*' | cut -d ' ' -f 2`
              rm -rf metadata*
              echo "pr_number=$pr_number" >> $GITHUB_OUTPUT
              echo "pr_base=$pr_base" >> $GITHUB_OUTPUT
            fi
          done

      - name: Determine build info
        id: build_info
        run: |
          requested_platforms=${{ inputs.platforms || (github.event_name == 'push' && 'linux/amd64,linux/arm64') || '' }}
          platforms="{\"ids\":[]}"
          if [ "$requested_platforms" != "" ]; then
            platform_id=`echo ${{ inputs.platforms }} | sed 's/linux\///g' | tr -d ' ' | tr , -`
            platforms=`echo $platforms | jq ".ids |= . + [\"$platform_id\"]"`
            platform={\"$platform_id\":\"${{ inputs.platforms }}\"}
            platforms=`echo $platforms | jq ". |= . + $platform"`
          else
            for input in linux/arm64 linux/amd64; do
              platform_id=`echo $input | sed 's/linux\///g' | tr -d ' ' | tr , -`
              platforms=`echo $platforms | jq ".ids |= . + [\"$platform_id\"]"`
              platform={\"$platform_id\":\"$input\"}
              platforms=`echo $platforms | jq ". |= . + $platform"`
            done
          fi

          cache_base=${{ (github.event_name == 'push' && 'main') || inputs.cache_base || steps.pr_info.outputs.pr_base }}
          update_cache=${{ (github.event_name == 'workflow_dispatch' && inputs.update_registry_cache) || github.event_name == 'push' }}
          environment=${{ (github.event_name != 'workflow_run' && 'ghcr-deployment') || '' }}

          echo "cache_base=$cache_base" >> $GITHUB_OUTPUT
          echo "update_cache=$update_cache" >> $GITHUB_OUTPUT
          echo "platforms=$(echo $platforms)" >> $GITHUB_OUTPUT
          echo "requested_platforms=$requested_platforms" >> $GITHUB_OUTPUT
          echo "environment=$environment" >> $GITHUB_OUTPUT

  devdeps:
    name: Build dev dependencies
    needs: metadata
    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'push' && github.event.created) || (github.event_name == 'workflow_run' && needs.metadata.outputs.pull_request_number != '')
    strategy:
      matrix:
        platform: ${{ fromJson(needs.metadata.outputs.platforms).ids }}
        toolchain: [llvm, clang16, gcc12]
      fail-fast: false
    uses: ./.github/workflows/dev_environment.yml
    with:
      platforms: ${{ fromJson(needs.metadata.outputs.platforms)[format('{0}', matrix.platform)] }}
      dockerfile: build/devdeps.Dockerfile
      toolchain: ${{ matrix.toolchain }}
      registry_cache_from: ${{ needs.metadata.outputs.cache_base }}
      registry_cache_update: ${{ needs.metadata.outputs.update_cache }}
      registry_cache_update_only: ${{ github.event_name == 'workflow_run' }}
      pull_request_number: ${{ needs.metadata.outputs.pull_request_number }}
      pull_request_commit: ${{ needs.metadata.outputs.pull_request_commit }}
      environment: ${{ needs.metadata.outputs.environment }}
      # needed only for the cloudposse GitHub action
      matrix_key: ${{ matrix.platform }}-${{ matrix.toolchain }}

  wheeldeps:
    name: Build wheel dependencies
    needs: metadata
    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'push' && github.event.created) || (github.event_name == 'workflow_run' && needs.metadata.outputs.pull_request_number != '')
    uses: ./.github/workflows/dev_environment.yml
    with:
      dockerfile: build/devdeps.manylinux.Dockerfile
      toolchain: gcc11
      build_args: |
        manylinux_image=quay.io/pypa/manylinux_2_28_x86_64:latest
        distro=rhel8
      registry_cache_from: ${{ needs.metadata.outputs.cache_base }}
      registry_cache_update: ${{ needs.metadata.outputs.update_cache }}
      registry_cache_update_only: ${{ github.event_name == 'workflow_run' }}
      pull_request_number: ${{ needs.metadata.outputs.pull_request_number }}
      pull_request_commit: ${{ needs.metadata.outputs.pull_request_commit }}
      environment: ${{ needs.metadata.outputs.environment }}

  openmpi:
    name: Build Open MPI
    needs: metadata
    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'push' && github.event.created) || (github.event_name == 'workflow_run' && needs.metadata.outputs.pull_request_number != '')
    strategy:
      matrix:
        platform: ${{ fromJson(needs.metadata.outputs.platforms).ids }}
      fail-fast: false
    uses: ./.github/workflows/dev_environment.yml
    with:
      platforms: ${{ fromJson(needs.metadata.outputs.platforms)[format('{0}', matrix.platform)] }}
      dockerfile: build/devdeps.ompi.Dockerfile
      registry_cache_from: ${{ needs.metadata.outputs.cache_base }}
      registry_cache_update: ${{ needs.metadata.outputs.update_cache }}
      registry_cache_update_only: ${{ github.event_name == 'workflow_run' }}
      environment: ${{ needs.metadata.outputs.environment }}
      # needed only for the cloudposse GitHub action
      matrix_key: ${{ matrix.platform }}

  dispatch:
    name: Dispatch deployments
    needs: [metadata, devdeps, wheeldeps, openmpi]
    if: github.event_name == 'workflow_run'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/github-script@v6
        with:
          # We want this dispatch to trigger additional workflows.
          github-token: ${{ secrets.REPO_BOT_ACCESS_TOKEN }}
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'deployments.yml',
              ref: '${{ needs.metadata.outputs.pull_request_commit }}',
              inputs: {
                platforms: 'linux/arm64,linux/amd64'
                cache_base: '${{ needs.metadata.outputs.cache_base }}',
              },
            })

  # This job is needed only when using the cloudposse GitHub action to read
  # the output of a matrix job. This is a workaround due to current GitHub
  # limitations that may not be needed if the work started here concludes:
  # https://github.com/actions/runner/pull/2477
  config:
    name: Configure build
    needs: [metadata, devdeps]
    if: github.event_name != 'workflow_run'
    runs-on: ubuntu-latest

    outputs:
      json: "${{ steps.read_json.outputs.result }}"
      base_image: ${{ fromJson(steps.read_json.outputs.result).image_hash[format('{0}-gcc12', steps.build_info.outputs.platform_key)] }}
      toolchain: gcc12

    steps:
      - uses: cloudposse/github-action-matrix-outputs-read@0.1.1
        id: read_json
        with:
          matrix-step-name: dev_environment

      - id: build_info
        run: |
          platform_key=`echo "${{ needs.metadata.outputs.requested_platforms }}" | sed 's/linux\///g' | tr -d ' ' | tr , -`
          echo "platform_key=$platform_key" >> $GITHUB_OUTPUT

  extdevdeps:
    name: Create dev environment
    needs: [metadata, config, openmpi]
    uses: ./.github/workflows/dev_environment.yml
    with:
      platforms: ${{ needs.metadata.outputs.requested_platforms }}
      dockerfile: build/devdeps.ext.Dockerfile
      toolchain: ${{ needs.config.outputs.toolchain }}
      build_args: |
        base_image=${{ needs.config.outputs.base_image }}
        ompidev_image=${{ needs.openmpi.outputs.image_hash }}
      registry_cache_from: ${{ needs.metadata.outputs.cache_base }}
      registry_cache_update: ${{ needs.metadata.outputs.update_cache }}
      environment: ${{ needs.metadata.outputs.environment }}

  docker_images:
    name: Create Docker images
    needs: [metadata, extdevdeps, openmpi]
    uses: ./.github/workflows/docker_images.yml
    secrets: inherit
    with:
      platforms: ${{ needs.metadata.outputs.requested_platforms }}
      ompidev_image: ${{ needs.openmpi.outputs.image_hash }}
      devdeps_image: ${{ needs.extdevdeps.outputs.image_hash }}
      environment: ghcr-deployment
      build_docs: true
      create_release: ${{ inputs.create_release }}

  python_wheels:
    name: Create Python wheels
    needs: wheeldeps
    if: github.event_name != 'workflow_run'
    strategy:
      matrix:
        python_version: ['3.8', '3.9', '3.10', '3.11']
      fail-fast: false
    uses: ./.github/workflows/python_wheels.yml
    with:
      python_version: ${{ matrix.python_version }}
      devdeps_image: ${{ needs.wheeldeps.outputs.image_hash }}
      # TODO: upload wheels to test-pypi - the push to pypi itself
      # should be done only by the publishing when creating a release.
      # See also: 
      # https://github.com/pypa/gh-action-pypi-publish
      # https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/
      # environment: pypi-deployment
